services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-container
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password@123"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
    networks:
      - medicine-network

  medicine-api:
    build:
      context: ./Medicine-Management-System
      dockerfile: Dockerfile
    container_name: medicine-app
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "https://+:8081;http://+:8080"
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: Password123
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    ports:
      - "5120:8080"
      - "7292:8081"
    volumes:
      - ${USERPROFILE}\.aspnet\https:/https/
    networks:
      - medicine-network
    restart: unless-stopped

  react-ui:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    container_name: react-ui
    ports:
      - "3000:3000"
    networks:
      - medicine-network
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - medicine-api

networks:
  medicine-network:
    driver: bridge

volumes:
  sql-data: