// <auto-generated />
using System;
using Medicine_Management_System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Medicine_Management_System.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Medicine_Management_System.Models.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Expirate_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Full Name");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Medicine");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Cipla",
                            Expirate_Date = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Paracetamol",
                            Note = "Fever",
                            Price = 2.5,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Sun Pharma",
                            Expirate_Date = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Amoxicillin",
                            Note = "Antibiotic",
                            Price = 5.0,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Cipla",
                            Expirate_Date = new DateTime(2027, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Paracetamol",
                            Note = "Pain relief",
                            Price = 2.5,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Sun Pharma",
                            Expirate_Date = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Amoxicillin",
                            Note = "Antibiotic",
                            Price = 5.0,
                            Quantity = 9
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Dr Reddy's",
                            Expirate_Date = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ibuprofen",
                            Note = "Anti-inflammatory",
                            Price = 3.2000000000000002,
                            Quantity = 75
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
